stages:
 - build
 - test
build:
 stage: build
 script:
  - echo "Building"
  - apt-get update -qy
  - apt-get install -y python3 python3-dev python3-pip
  - pip3 install -r requirements.txt
test:
 stage: test
 script:
  - echo "Testing"
  - python progetto/test_score.py

 
